config/routes.rb
Rails.application.routes.draw do
  resources :forecasts

  root 'forecasts#new'

end

app/models/forecast.rb
require 'date'

class Forecast < ActiveRecord::Base

  attr_accessor :zip_output, 
                :weather_output, 
                :url, 
                :city_slug, 
                :temperature, 
                :hours, 
                :humidity, 
                :heat_index, 
                :wind_speed, 
                :wind_chill,
                :now_statement,
                :conditions_icon,
                :discrepancy_index,
                :discrepancy_statement,
                :first_discrepancy,
                :status,
                :t_shirt_statement,
                :uv_index,
                :uv_statement,
                :all_hours,
                :max_time,
                :max_day,
                :seasonal_index,
                :today,
                :day_in_36_hours,
                :forecast_data,
                :unformatted_hours

  def process_forecast
    store_zip_output
    store_location
    collect_data
  end

  def store_location
    self.store_city
    self.store_state
    self.city_to_slug
    self.to_url
  end

  def zip_output
    ZipCodes.identify("#{self.zipcode}")
  end

  def store_zip_output
    self.zip_output = zip_output
  end

  def valid_zip? 
     zip_output != nil
  end

  def store_city 
    self.city = zip_output[:city]
  end

  def store_state 
    self.state = zip_output[:state_code]
  end

  def city_to_slug 
    self.city_slug = city.downcase.gsub(" ", "_")
  end

  def to_url 
    api_token = ENV["weather_api"]
    self.url = "http://api.wunderground.com/api/#{api_token}/hourly/q/#{state}/#{city_slug}.json"
  end

  def scrape_json 
    api_response = open(url).read
    self.forecast_data = JSON.parse(api_response)
  end

  def filter_array_length(array)
    array.values_at(* array.each_index.select {|i| i.even?})
  end
  
  def collect_unformatted_hours
    self.unformatted_hours = filter_array_length (forecast_data["hourly_forecast"].collect {|hash| hash["FCTTIME"]["hour"].to_i })
  end

  def collect_hours 
    self.hours = []
    collect_unformatted_hours
    unformatted_hours.each do |hour|
      case hour
      when 0 then hour = "midnight"
      when 12 then hour = "noon"
      when 13..23 then hour = "#{hour.to_i - 12}pm" 
      else hour = "#{hour.to_i}am"
      end
      self.hours << hour
    end
  end

  def day_today
    @time.between?(15,24) ? self.today = "tonight" : self.today = "today"
  end

  def day_in_36_hours
    @time.between?(1,12) ? self.day_in_36_hours = "tomorrow" : self.day_in_36_hours = "the day after tomorrow"
  end

  def collect_humidity 
    self.humidity = forecast_data["hourly_forecast"].collect {|hash| hash["humidity"]}
    self.humidity = filter_array_length(self.humidity)
  end

  def collect_temperature 
    self.temperature = forecast_data["hourly_forecast"].collect {|hash| hash["temp"]["english"].to_i}
    self.temperature = filter_array_length(self.temperature)
  end

  def collect_wind_speed 
    self.wind_speed = forecast_data["hourly_forecast"].collect {|hash| hash["wspd"]["english"].to_i}
    self.wind_speed = filter_array_length(self.wind_speed)
  end

  def collect_status 
    self.status = forecast_data["hourly_forecast"].collect {|hash| hash["wx"]}
    self.status = filter_array_length(self.status)
  end

  def collect_data
    scrape_json
    store_zip_output
    collect_hours
    collect_temperature
    collect_humidity
    collect_heat_index
    collect_wind_speed
    collect_wind_chill
    collect_seasonal_index
    collect_status
    collect_uv_index
    set_now_statement
    set_conditions_icon
    discrepancy?
    t_shirt_weather?
    need_suncreen?
    day_today
    day_in_36_hours
    collect_unformatted_hours
  end

  # http://www.wpc.ncep.noaa.gov/html/heatindex_equation.shtml
  def collect_heat_index
    heat_index_calculator = HeatIndexCalculator.new(self)
    self.heat_index = heat_index_calculator.calculate
  end 

  # http://www.srh.noaa.gov/images/epz/wxcalc/windChill.pdf
  def collect_wind_chill
    wind_chill_calculator = WindChillCalculator.new(self)
    self.wind_chill = wind_chill_calculator.calculate
  end 

  def collect_seasonal_index
    self.seasonal_index = []
    temperature.each_with_index do |temp, index|
      if temp >= 70
        self.seasonal_index << heat_index[index]
      elsif temp > 50
        self.seasonal_index << temperature[index]  
      else self.seasonal_index << wind_chill[index]
      end
    end
  end

  def set_time              
    @time = Time.now.to_a[2]
  end

  def set_now_statement
   temperature_now = temperature[0].to_i 
   humidity_now = humidity[0].to_i 
   if sleepy_time?
      sleepy_time_array = ["Night time. Dear Lord. Don't you sleep?", "Why are you not in bed?!", "Up late, are we?"]
      self.now_statement = sleepy_time_array.sample
   else
     if very_hot? && humid?
          if clear_or_sunny?
            hot_and_humid_array = ["Mother Nature off her meds today.", "Hot and gross! Like a wet gym sock left out in a hamper.", "Like hot molasses.", "I am done reporting the weather. This sucks.", "No greenhouse necessary.", "You are my Sunshine."]
            self.now_statement = hot_and_humid_array.sample
          else
            hot_and_humid_array = ["Mother Nature off her meds today.", "Hot and gross! Like a wet gym sock left out in a hamper.", "Like hot molasses.", "I am done reporting the weather. This sucks.", "No greenhouse necessary."]
            self.now_statement = hot_and_humid_array.sample
          end
     elsif very_hot? && comfortably_humid?
        if clear_or_sunny?
          hot_and_ok_array = ["Make sure to hydrate.", "Extremely hot! But at least not too humid.", "I don't know everything, but I do know it's nice out.", "You are the sunshine of my life."]
          self.now_statement = hot_and_ok_array.sample
        else
          hot_and_ok_array = ["Make sure to hydrate.", "Extremely hot! But no sticking to the bus seat today.", "I don't know everything, but I do know it's nice out."]
          self.now_statement = hot_and_ok_array.sample
        end
     elsif very_hot?
         hot_and_dry_array = ["Where are you, Death Valley?!", "HOT.DRY. Are you on Venus?", "Insert amazing weather forecast here. Sorry, it sucks out.", "Weather is misbehaving.", "Only leave the indoors for emergency beer runs."]
         self.now_statement = hot_and_dry_array.sample
     elsif reasonably_hot? && humid?
         hot_and_humid_array = ["Hot and gross! Consider a move to Antarctica.", "I hear Lake Titicaca is very pleasant this time of year.", "New goal: become a penguin and move somewhere cold.", "Buy a dehumidifier and turn your AC on. Don't move until the weather changes."]
         self.now_statement = hot_and_humid_array.sample
     elsif reasonably_hot? && comfortably_humid?
         hot_and_comfortable_array = ["Eek pretty hot! But at least it's not too humid.", "Hot. Not Muggy. Go play outdoors.", "HOT. Be happy it is not humid.", "Pool party time!!!"] 
         self.now_statement = hot_and_comfortable_array.sample
     elsif reasonably_hot?
        if clear_or_sunny?
          reasonably_hot_array = ["Pretty darn hot, with dry heat!", "I feel like an old sweatshirt, fresh out of a dryer.", "Like being inside a bread oven, minus yummy bread.", "Hot'n'Dry.", "You are the sunshine of my life."]  
          self.now_statement = reasonably_hot_array.sample    
        else
          reasonably_hot_array = ["Pretty darn hot, with dry heat!", "I feel like an old sweatshirt, fresh out of a dryer.", "Like being inside a bread oven, minus yummy bread.", "Hot'n'Dry."]  
          self.now_statement = reasonably_hot_array.sample
        end
     elsif warm? && humid?
         warm_and_humid_array = ["Decent weather out, but so humid you could grow moss.", "It would be SO much nicer if it were not as humid.", "Thick'n'humid."]
         self.now_statement = warm_and_humid_array.sample
     elsif warm? && comfortably_humid?
          if clear_or_sunny?
            pleasant_array = ["Pleasant as shit out.", "Weather working for YOU today.", "Goldilocks approved weather today", "Bottle this weather and save it for a rainy day.", "Wow, the weather is totally nice!", "You are my sunshine, my only sunshine."]
            self.now_statement = pleasant_array.sample
          else
            pleasant_array = ["Pleasant as shit out.", "Weather working for YOU today.", "Goldilocks approved weather today", "Bottle this weather and save it for a rainy day.", "Wow, the weather is totally nice!"]
            self.now_statement = pleasant_array.sample
          end
     elsif warm?
         warm_and_dry_array = ["Every once in a while, you can stop bitching about the weather. Today is that day. You are that person.", "My job is easy today. Now go enjoy yo'selves!", "Mmmm, good weather."]
         self.now_statement = warm_and_dry_array.sample
     elsif comfortable?
       comfortable_array = ["Not exactly warm. Layer up.", "Don't you wish you were somewhere warm right now?", "I hear mulled wine is nice for this weather.", "Hot tea. Lots of it. Maybe with some whisky."]
       self.now_statement = comfortable_array.sample
     else 
       cold_array = ["COLD. Like penguin cold.", "Break out your trusty Uggs ladies / Buffalo pelts gents.", "'Tis the season to winterize yourself.", "Bout time to look into that Bahamas vacation."]
       self.now_statement = cold_array.sample
     end 
   end 
 end

  def temperature_now
    seasonal_index[0].to_i
  end

  def humidity_now
    humidity[0].to_i
  end

  def humid?
    humidity_now >= 60
  end

  def comfortably_humid?
    humidity_now.between?(43,59)
  end


  def dry_air?
    humidity_now <= 42
  end

  def very_hot?
    temperature_now >= 90
  end

  def reasonably_hot?
    temperature_now >= 80 && temperature_now <= 89
  end
 
  def warm? 
    temperature_now >= 60 && temperature_now <= 79
  end

  def comfortable?
    temperature_now >= 42 && temperature_now <= 59
  end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController

  def new
    @forecast = Forecast.new
  end

  def create
    @forecast = Forecast.new(zipcode: params["forecast"]["zipcode"])
    if @forecast.valid_zip?
      @forecast.save
      redirect_to forecast_path(@forecast)
    else 
      flash[:notice] = "Please enter a valid zip code."
      redirect_to new_forecast_path
    end
  end

  def show
    @forecast = Forecast.find(params[:id])
    @forecast.process_forecast
  end

end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/index.html.erb
<div class = 'row top-padding'>
  <div class = 'col-md-12 padding-head' >
    <h1 class = 'text-center c-font bold'>
      Today's (Real) Weather
    </h1>
  </div>
</div>
<div class='row'>
  <div class="col-md-4 col-md-offset-4 top-padding text-center">
    <%= form_for @forecast, url: forecasts_path, html: {class: "navbar-form navbar-nav"} do |f| %>
      <%= f.text_field :zipcode, :placeholder => "Enter Your Zipcode", class: "form-control" %>
      <%= f.submit "Get your Forecast!", class: "btn btn-default" %>
    <% end %>
  </div>
</div>
<% if flash[:notice] %>
  <center><div class="notice">
    <%= flash[:notice] %>
  </div></center>
<% end %>
<div class= 'spacer'>
</div>

app/views/forecasts/new.html.erb
<div class = 'row top-padding'>

  <div class = 'col-md-12 padding-head' >
    <h1 class = 'text-center c-font bold'>
      Get Your (Real) Weather
    </h1>
  </div>

  <div class='row'>
    <div class="col-md-4 col-md-offset-4 top-padding text-center">
      <%= form_for @forecast, url: forecasts_path, html: {class: "navbar-form navbar-nav"} do |f| %>
      <%= f.text_field :zipcode, :placeholder => "Enter Your Zipcode", class: "form-control" %>
      <%= f.submit "Get your Forecast!", class: "btn btn-default" %>
    <% end %>
    </div>
  </div>

  <% if flash[:notice] %>
    <center>
      <div class="notice"><%= flash[:notice] %>
      </div>
    </center>
  <% end %>

  <div class= 'spacer'>
  </div>

</div>

app/views/forecasts/show.html.erb
<div class = 'row top-padding'>
  <div class = 'col-md-12 padding-head' >
    <h1 class = 'text-center c-font bold'>
      <%=@forecast.now_statement%> 
    </h1>
    <h2 class = 'text-center'>
      <%=@forecast.city %>, <%= @forecast.state %> (<%= @forecast.zipcode%>) 
    </h2>
    <center>
    <h3>
      <a href="#" data-toggle="popover" title="What the Weathermen Won't Tell You" data-content="We use advanced calculations to provide you with real-time forecast details to reflect how it truly feels outside, not just the current temperature. We strive to provide a healthy dose of humor as well as relevant alerts for heat index, wind chill, UV, and more.">
      What is this about?
      </a>
    </h3>
    </center>
  </div>
 </div>

<div class = 'data-container'>
  <div class = "row top-padding">
    <div class= "col-md-5">
      <div class = "padding">
        <center>
        <h4 class = 'dash-font'> <span class= 'red'> Perceived Temperature vs.</span></h4>
        <h4 class = 'dash-font'> Actual Temperature </h4>
        </center>
        <%= line_chart @forecast.data_temps, @forecast.options_temps %>
      </div>
    </div>
    <div class= "col-md-2"></div>
                                  
    <div class = "col-md-5">
      <div class = "padding dash-font"> 
        <p> Right now it's <%=@forecast.temperature[0]%>°F,  <%=@forecast.humidity[0]%>% humidity <img src ="<%=@forecast.conditions_icon%>"> </p>
        <% if @forecast.current_temp_dif? %>
          <br><p>Feels like <%=@forecast.seasonal_index[0]%>°F. </p>
        <%end%>
        <br>
        <p><%=@forecast.wind_statement%></p>
        <br>
        <p><%= @forecast.discrepancy_statement %></p>
        <br>
        <p><%= @forecast.t_shirt_statement %></p>
        <br>
        <p><%= @forecast.uv_statement %></p>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class="form-horizontal">
      <%= form_for @forecast, url: forecasts_path, method: "POST", html: {class: "navbar-form navbar-nav"} do |f| %>
        <%= f.text_field :zipcode, :placeholder => "Enter Your Zipcode", class: "form-control" %>
        <%= f.submit "Get Another Forecast!", class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>